version: "3.7"

services:
  ehe-tenandayo:
    container_name: ehe-tenandayo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$PORT:$PORT"
    env_file: .env
    restart: always
